<?php
error_reporting(-1);
ini_set('display_errors', 'On');
header('Content-type: application/xml');
header('Pragma: public');
header('Cache-Control: private');
header('Expires: -1');
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo PHP_EOL;
require realpath($_SERVER['DOCUMENT_ROOT']).'/includes/init_trigger.inc.php';
/*
echo '<?xml-stylesheet type="text/xsl" href="https://'.$_SERVER['HTTP_HOST'].'/sitemap.xsl" ?>';
echo PHP_EOL;
*/
echo '<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="https://www.w3.org/1999/xhtml" xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0">';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?lang=vi</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?lang=en</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?lang=ru</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?lang=es</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?lang=zh</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?lang=ja</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','vi').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','en').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ru').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','es').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','zh').'"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/','ja').'"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/vi/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.$_SERVER['HTTP_HOST'].'/en/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.$_SERVER['HTTP_HOST'].'/ru/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.$_SERVER['HTTP_HOST'].'/es/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.$_SERVER['HTTP_HOST'].'/zh/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.$_SERVER['HTTP_HOST'].'/ja/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.$_SERVER['HTTP_HOST'].'/vi/"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/en/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.$_SERVER['HTTP_HOST'].'/vi/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.$_SERVER['HTTP_HOST'].'/ru/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.$_SERVER['HTTP_HOST'].'/es/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.$_SERVER['HTTP_HOST'].'/zh/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.$_SERVER['HTTP_HOST'].'/ja/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.$_SERVER['HTTP_HOST'].'/en/"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/ru/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.$_SERVER['HTTP_HOST'].'/vi/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.$_SERVER['HTTP_HOST'].'/en/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.$_SERVER['HTTP_HOST'].'/es/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.$_SERVER['HTTP_HOST'].'/zh/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.$_SERVER['HTTP_HOST'].'/ja/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.$_SERVER['HTTP_HOST'].'/ru/"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/es/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.$_SERVER['HTTP_HOST'].'/vi/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.$_SERVER['HTTP_HOST'].'/en/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.$_SERVER['HTTP_HOST'].'/ru/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.$_SERVER['HTTP_HOST'].'/zh/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.$_SERVER['HTTP_HOST'].'/ja/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.$_SERVER['HTTP_HOST'].'/es/"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/zh/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.$_SERVER['HTTP_HOST'].'/vi/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.$_SERVER['HTTP_HOST'].'/en/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.$_SERVER['HTTP_HOST'].'/ru/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.$_SERVER['HTTP_HOST'].'/es/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.$_SERVER['HTTP_HOST'].'/ja/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.$_SERVER['HTTP_HOST'].'/zh/"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/ja/</loc>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.$_SERVER['HTTP_HOST'].'/vi/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.$_SERVER['HTTP_HOST'].'/en/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.$_SERVER['HTTP_HOST'].'/ru/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.$_SERVER['HTTP_HOST'].'/es/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.$_SERVER['HTTP_HOST'].'/zh/"/>';
echo PHP_EOL;
echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.$_SERVER['HTTP_HOST'].'/ja/"/>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/bmi/</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/xemngay/</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/game/</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/proverbs/</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/what-is-biorhythm/</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/nhip-sinh-hoc-la-gi/</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?p=bmi</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?p=lunar</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?p=pong</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
echo PHP_EOL;
echo '<url>';
echo PHP_EOL;
echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?p=race</loc>';
echo PHP_EOL;
echo '<changefreq>monthly</changefreq>';
echo PHP_EOL;
echo '<priority>0.8</priority>';
echo PHP_EOL;
echo '<mobile:mobile/>';
echo PHP_EOL;
echo '</url>';
$users = load_all_array('nsh_users');
usort($users,'sort_name_ascend');
$count = count($users);
for ($i = 0; $i < $count; ++$i) {
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.$_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&amp;dob='.$users[$i]['dob'].'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '<mobile:mobile/>';
  echo PHP_EOL;
  echo '</url>';
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '<mobile:mobile/>';
  echo PHP_EOL;
  echo '</url>';
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '<mobile:mobile/>';
  echo PHP_EOL;
  echo '</url>';
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '<mobile:mobile/>';
  echo PHP_EOL;
  echo '</url>';
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '</url>';
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '<mobile:mobile/>';
  echo PHP_EOL;
  echo '</url>';
  echo PHP_EOL;
  echo '<url>';
  echo PHP_EOL;
  echo '<loc>https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'</loc>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="vi" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'vi').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="en" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'en').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ru" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ru').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="es" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'es').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="zh" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'zh').'"/>';
  echo PHP_EOL;
  echo '<xhtml:link rel="alternate" hreflang="ja" href="https://'.change_url_lang($_SERVER['HTTP_HOST'].'/?fullname='.str_replace(' ','+',$users[$i]['name']).'&dob='.$users[$i]['dob'],'ja').'"/>';
  echo PHP_EOL;
  echo '<changefreq>monthly</changefreq>';
  echo PHP_EOL;
  echo '<priority>0.8</priority>';
  echo PHP_EOL;
  echo '<mobile:mobile/>';
  echo PHP_EOL;
  echo '</url>';
}
echo PHP_EOL;
echo '</urlset>';
?>